Repository doutatsu/kenmei, pull requests merged in 2020-10, with the labels that each got.

#405 Add input form components
  .env
  package.json
  src/components/TheImporters.vue
  src/components/TheResetPassword.vue
  src/components/TheSignIn.vue
  src/components/TheSignUp.vue
  src/components/base_components/BaseFormCheckbox.vue
  src/components/base_components/BaseFormInput.vue
  src/components/icons/IconLink.vue
  src/components/icons/IconMail.vue
  src/components/icons/IconSearch.vue
  src/components/manga_entries/AddMangaEntry.vue
  src/components/settings/SettingsAccountPasswordSection.vue
  src/components/settings/SettingsAccountProfileSection.vue
  src/locales/en.json
  src/packs/main.js
  src/plugins/i18n.js
  src/views/MangaList.vue
  src/views/ResetPassword.vue
  tests/__mocks__/i18n.js
  tests/components/TheImporters.spec.js
  tests/components/TheResetPassword.spec.js
  tests/components/TheSignIn.spec.js
  tests/components/TheSignUp.spec.js
  tests/components/base_components/BaseFormInput.spec.js
  tests/components/manga_entries/AddMangaEntry.spec.js
  tests/components/settings/SettingsAccountPasswordSection.spec.js
  tests/components/settings/SettingsAccountProfileSection.spec.js
  tests/setup.js
  tests/views/ResetPassword.spec.js
  vue.config.js
  yarn.lock
Labels: enhancement

#409 Reset validations on modal closure
  src/components/TheImporters.vue
  src/components/manga_entries/AddMangaEntry.vue
Labels: bug

#410 Fix warnings in tests
  tests/__mocks__/vue-scrollto.js
  tests/views/MangaList.spec.js
Labels: clean up

#413 Add indeterminate state to base checkbox
  src/components/base_components/BaseFormCheckbox.vue
Labels: enhancement

#422 Add ability to add manga by search
  .eslintrc.js
  package.json
  src/components/base_components/BaseFormAutocomplete.vue
  src/components/base_components/BaseFormInput.vue
  src/components/base_components/BaseTabs.vue
  src/components/manga_entries/AddMangaEntry.vue
  src/components/manga_entries/AddMangaEntryBySearch.vue
  src/packs/main.js
  src/services/api.js
  src/services/endpoints/v1/manga_series.js
  tests/components/base_components/BaseFormAutocomplete.spec.js
  tests/components/base_components/BaseFormInput.spec.js
  tests/components/base_components/BaseTabs.spec.js
  tests/components/manga_entries/AddMangaEntry.spec.js
  tests/components/manga_entries/AddMangaEntryBySearch.spec.js
  tests/factories/index.js
  tests/factories/mangaSeries.js
  tests/factories/mangaSource.js
  tests/services/api.spec.js
  tests/services/endpoints/v1/manga_series.spec.js
  yarn.lock
Labels: enhancement

#428 Fix typo in Account Termination section
  src/components/settings/SettingsAccountTerminationSection.vue
Labels: bug

#429 Fix not setting correct target for body lock
  src/components/base_components/BaseModal.vue
Labels: bug

#430 Add ability to clear local search
  src/components/base_components/BaseFormInput.vue
  src/components/icons/IconCross.vue
  src/views/MangaList.vue
Labels: enhancement

#431 Add missing right margin
  src/components/base_components/BaseFormInput.vue
Labels: bug

#432 Switch to using a method for classes to fix cache
  src/components/base_components/BaseFormInput.vue
Labels: bug

#433 Add Asura Scans banner
  src/assets/source_logos/asura_scans_logo.jpg
  src/assets/sources.json
  src/components/landing_page/LandingPageStats.vue
Labels: enhancement

#434 Validate search term not to be a URL
  src/components/base_components/BaseFormAutocomplete.vue
  src/components/manga_entries/AddMangaEntry.vue
  src/components/manga_entries/AddMangaEntryBySearch.vue
  src/locales/en.json
  tests/components/manga_entries/AddMangaEntryBySearch.spec.js
Labels: enhancement

#435 Refactor SettingMangaListTags Component
  src/components/settings/SettingsMangaListTags.vue
  src/locales/en.json
  tests/components/settings/SettingsMangaListTags.spec.js
Labels: enhancement

#436 Bump babel jest to 26.6.1
  package.json
  yarn.lock
Labels: dependencies

#438 Improve autocomplete and add manga entry by search
  .eslintrc.js
  src/components/base_components/BaseFormAutocomplete.vue
  src/components/manga_entries/AddMangaEntry.vue
  src/components/manga_entries/AddMangaEntryBySearch.vue
  tests/components/base_components/BaseFormAutocomplete.spec.js
  tests/components/manga_entries/AddMangaEntry.spec.js
  tests/components/manga_entries/AddMangaEntryBySearch.spec.js
Labels: bug, enhancement

#450 Bump tailwind-ui library to 0.6.2
  package.json
  yarn.lock
Labels: dependencies

#451 Fix debounce on BaseFormAutocomplete
  tests/__mocks__/lodash/debounce.js
  tests/components/base_components/BaseFormAutocomplete.spec.js
  tests/components/manga_entries/AddMangaEntry.spec.js
  tests/components/manga_entries/AddMangaEntryBySearch.spec.js
  tests/components/settings/SettingsMangaListTags.spec.js
Labels: hacktoberfest-accepted
